/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#04151e",
        "surface-variant": "#263740",
        "secondary-container": "#5028ae",
        "primary": "#a6c8ff",
        "on-secondary-fixed": "#21005e",
        "tertiary-fixed-dim": "#00e29e",
        "secondary-fixed-dim": "#cebdff",
        "primary-container": "#2d91ff",
        "surface-tint": "#a6c8ff",
        "on-tertiary-fixed": "#002114",
        "on-primary-fixed": "#001c3b",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#d3e5f1",
        "surface-bright": "#2b3b45",
        "tertiary": "#00e29e",
        "inverse-surface": "#d3e5f1",
        "secondary-fixed": "#e8ddff",
        "error": "#ffb4ab",
        "outline": "#c7cfc33c",
        "surface-container-high": "#1b2c35",
        "background": "#04151e",
        "tertiary-fixed": "#47ffb8",
        "tertiary-container": "#00a572",
        "secondary": "#cebdff",
        "surface-container-lowest": "#011018",
        "on-background": "#d3e5f1",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#5028ae",
        "primary-fixed": "#d5e3ff",
        "on-primary-container": "#002a54",
        "inverse-on-surface": "#22333c",
        "on-primary": "#003060",
        "outline-variant": "#404753",
        "on-tertiary": "#003824",
        "error-container": "#93000a",
        "on-secondary-container": "#bea8ff",
        "surface-container": "#10222a",
        "on-error": "#690005",
        "surface-container-low": "#0c1e26",
        "primary-fixed-dim": "#a6c8ff",
        "on-tertiary-container": "#00311f",
        "on-surface-variant": "#c0c7d6",
        "surface": "#04151e",
        "surface-container-highest": "#263740",
        "inverse-primary": "#005eb1",
        "on-secondary": "#390094",
        "on-primary-fixed-variant": "#004787"
      },
      fontFamily: {
        "headline": ["Syne", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "space": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        "full": "0.75rem",
        "round-full": "9999px"
      },
    },
  },
  plugins: [],
}


